# Generated by Django 5.1.3 on 2025-01-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_customer_confpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup', models.CharField(max_length=100)),
                ('delivery', models.CharField(max_length=100)),
                ('goodtype', models.CharField(max_length=100)),
                ('vehicletype', models.CharField(max_length=100)),
                ('pickupdate', models.DateField()),
                ('distance', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
