# Generated by Django 5.1.3 on 2025-01-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0003_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.CharField(max_length=5000000),
        ),
    ]
