# Generated by Django 5.1.3 on 2025-01-06 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_alter_booking_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp1.customer'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='booking',
            name='distance',
            field=models.FloatField(),
        ),
    ]
