# Generated by Django 5.1.3 on 2025-01-07 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0011_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='name',
        ),
    ]
