# Generated by Django 5.1.3 on 2025-01-07 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0012_rename_user_booking_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='name',
        ),
    ]
