# Generated by Django 5.1.3 on 2025-01-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0014_booking_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
