# Generated by Django 5.1.3 on 2025-01-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0016_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
