# Generated by Django 5.2.1 on 2026-04-25 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0019_booking_paid_at_booking_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("in_transit", "In Transit"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="confirmed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_lat",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_lng",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="driver_phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="estimated_delivery",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="last_location_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booking",
            name="special_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
