# Generated by Django 5.2.1 on 2026-04-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp1", "0020_booking_booking_status_booking_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="driver_share_key",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
